### ISSUE TITLE
Open discussion (e.g. Discourse)

### ISSUE THREAD

**Issue by bwbroersma** [minvws/nl-covid19-notification-app-coordination#14]
Like I and many others have proposed already many times [[1](https://codefornl.slack.com/archives/C011R4NCFMJ/p1589309142308900), [2](https://codefornl.slack.com/archives/C011R4NCFMJ/p1589309211309800), [3](https://codefornl.slack.com/archives/C011R4NCFMJ/p1589536911413100), [4](https://codefornl.slack.com/archives/C011R4NCFMJ/p1589541380430200), [5](https://codefornl.slack.com/archives/C011R4NCFMJ/p1589818523147300), [6](https://codefornl.slack.com/archives/C011R4NCFMJ/p1590603588375400)], can we use a publicly open discussion software, like [Discourse](https://www.discourse.org/) to have an orderly discussion, instead the current walled chaotic Slack chat?

**Comment by ijansch** [comment]
We prefer to keep the ‘official’ discussion on GitHub (issues and/or pull requests) as we can ensure things like the CLA are in place. For now, we can reevaluate this when necessary so I’ll leave this open for further comments.

**Comment by arianvp** [comment]
I think this was mostly meant as a critque of the discussions on Slack; which are _not_ easy to follow at all; not on the discussions happening on GitHub.

Do you propose shifting more of those Slack discussions to Github issues?

**Comment by bwbroersma** [comment]
Spot on @arianvp, my point was to remove the Slack that is used for architectural discussions, mentions in [the new issue message](https://github.com/minvws/nl-covid19-notification-app-coordination/blob/c6dc97a4c6c48c1cfecb29b7657921cf977f54f1/.github/config.yml#L25-L26) and [`CONTRIBUTING.md`](https://github.com/minvws/.github/blob/47745f5318f47cb54bf99f562f5366e4c87143c7/CONTRIBUTING.md#engaging-in-our-project). It's okay to use a quick chat, but it should not be used for 'storing' discussions/information or public announcements.

The major general service announcements that are now done in some Slack threads, *e.g. that GitHub is a fork of an internal Azure DevOps, with a preferably daily (manual/automatic) synchronizing to GitHub.* [[1](https://codefornl.slack.com/archives/C011R4NCFMJ/p1591124028067600?thread_ts=1590668629.424500)] are missed, also [this post of May 15th](https://codefornl.slack.com/archives/C011R4NCFMJ/p1589525382363300?thread_ts=1589398401.087300) was missed by many because it was buried in an old -out of view- Slack thread. Therefore not having informed the whole community and giving discrepancies in expectations that can later give disappointed and frustrations.

The current way Slack is used for announcements is not ideal, also discussions are hard to find because:
- the first message isn't always a 'topic post'
- if you didn't participated in an old thread, they will not be visible in the Slack Threads view (there is no new-reply bump of a thread)

**Comment by EdoPlantinga** [comment]
FYI @bwbroersma and me are collaborating on a document with the pro's and con's of staying in Slack (with improvements) or migrating elsewhere (Discourse or other). DM me on Slack (yeah, I know) if you want to join in.

**Comment by JolandaVerhoef** [comment]
@bwbroersma can we move this discussion to Slack and close the issue here?

**Comment by bwbroersma** [comment]
As long as it isn't solved that doesn't feel right since the whole point of moving the discussion of Slack that discussions get lost over there. Long term discussions in Slack don't exist at the moment.

I would love to continue with @EdoPlantinga to make it happen / improve. But currently there is zero progress on this topic.

**Comment by EdoPlantinga** [comment]
Closing this issue. We decided to stay in Slack. See https://docs.google.com/document/d/1Anfrry6NSHQJiWKS348GdD2svgHDJ6FJHLTNXp_qpMQ/edit#heading=h.reti3kvyss5e.
