### ISSUE TITLE
CLA might have far-reaching effects

### ISSUE THREAD

**Issue by jellelicht** [minvws/nl-covid19-notification-app-coordination#16]
NAL.

A section of the 1.00 version of the [CLA](https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md) clearly states:

> The Contributor hereby grants the Ministry a perpetual, worldwide, non-exclusive, sublicensable, irrevocable and unrestricted right of use to the Contributions. This right of use pertains to all intellectual property rights that could attach to the Contributions, which in any event includes copyrights, trademark rights, database rights and patents.

In a further section, this is specified as including  but not being limited to:
> sublicense the Contributions (including copies and adaptations thereof and derivative works) to any third party under the terms and conditions of the most recent version of the European Union Public Licence (EUPL) or a 'compatible licence' within the meaning of the EUPL.

My issue pertains to the 'unrestricted' clause of the first statement; it seems to me that by signing the CLA, I ostensibly give the Ministry a right to sublicense. This is clarified in the second snippet to also specifically include the EUPL, which is all dandy. 

My understanding is that the ministry has an unrestricted license when I contribute. They in turn specifically state that they can sublicense to third parties under EUPL & friends. Doesn't an unrestricted license also allow for unrestricted *re*licensing though, even to something very proprietary? It would be kind of silly if people contribute to this project believing that their contributions will definitely be a public good, only to find out that some very unexpected things can happen.

Please consider taking a page out of the playbook of your [German counterparts](https://github.com/corona-warn-app/cwa-documentation/blob/master/CONTRIBUTING.md#steps-to-contribute) and look into getting a more level playing field for everyone; 

My practical request is to simplify the CLA to oly require all contributions to be made under the EUPL(-compatible) license, and to leave out the legal mumbo-jumbo that does not seem to have the best interest of the Dear Contributor at heart.

**Comment by dirkx** [comment]
Bedankt voor de vraag - maak een notitie voor de FAQ om hier op in te gaan. 

Je punt is volledig terecht - de Duitse ASL/2 keuze laat ongebreideld gebruik in de industrie zonder enig voorbehoud toe.  Pure open source. Bruikbaar door en-ieder op elke manier voor elk doel zonder verplichtingen.

Bij de licentie keuze is echter meegenomen dat dit soort software en systemen niet zomaar 'industry' technologie is. Men geeft dus wat rekenschap van de bijzondere positie van dit soort bijzondere systemen en de positie van de overheid; en de verantwoordelijkheid aan de maatschappij die daar bij hoort.

**Comment by jellelicht** [comment]
Ik denk dat mijn punt verkeerd-om is aangekomen: mijn punt is dat de huidige CLA _alles_ lijkt toe te staan; ik kan me voorstellen dat ik juist wil dat mijn contributies _enkel_ onder EUPL (and friends) beschikbaar worden gemaakt, ook aan minvws. Als er dus iets ongebreidelde zaken toestaat, dan is het de huidige CLA.

**Comment by dirkx** [comment]
Ok - dat is een veel en veel complexere vraag - want dan zit je in de complexiteit van software lifecycles; en  wat je nodig hebt voor goed rentmeesterschap. Omdat je mogelijk dit soort code wil laten bewaren, op de zeer lange termijn, op plekke als een archief of bij een partij als NLNet haar Stichting Commons Conservatory (https://commonsconservancy.org). Weet niet of ik dat snel genoeg voor de eerste FAQ kan samenvatten. Maar zet hem op de lijst. Dank !

**Comment by jellelicht** [comment]
Kan er tenminste een commitment worden gemaakt dat welke license er dan ook gekozen wordt, dit ten minste een OSI-approved license zal zijn? Dat moet hopelijk genoeg ruimte geven voor goed rentmeesterschap.

**Comment by dirkx** [comment]
Ik dacht dat de huidige CLA dat in combinatie met de EUPL dat nog veel verder inperkte dan OSI du-jour. Ik kijk het even na.

**Comment by jellelicht** [comment]
Dat was mijn (waarschijnlijk niet goed onderbouwde) punt: uit mijn NAL interpretatie van de CLA tekst v1.0 haal ik dat je minvws een complete carte blanche geeft (maar zelf auteursrecht behoudt). Later wordt het licensen onder EUPL specifiek genoemd, maar in een opsomming voorafgegaan door "not limited to".

**Comment by dirkx** [comment]
Ja - en dat laatste moet er staan - wat we willen niet licenties van derden 'insweepen' als we er geen wezenlijk werk / deriviative work van maken; maar gebruiken 'as is' met alleen kleine edits.

We moeten maar eens brainstomer in een andere setting of er een soort 'EUPL' of ander 'open state' wrapup event moet komen (of een auto-trigger hiervoor in de (i)CLA - na N jaar dormant - automatisch gebeurt er 'X' waarbij de carte blanche vervalt omat je hem kennelijk niet meer nodig hebt. Waar 'X' zoiets is als definitief in het 'Stichting Commons Conservatory (https://commonsconservancy.org)' stoppen of soortgelijk.

En dan met partijen zoals die praten of ze dat kunnen accepteren zonder zelf een al te veel van die carte blanche te hebben om zelf weer te kunnen overdragen/veiligstellen als zij aan de natuurlijke einde van hun levensduur komen.

Want ik zie dit elders ook een puzzeln zijn - Bijvoorbeeld ASF software in de 'attic' die toch productie kritisch is voor een kleine gemeenschap.
