### ISSUE TITLE
[Meta] Shorten `newIssueWelcomeComment` text

### ISSUE THREAD

**Issue by bwbroersma** [minvws/nl-covid19-notification-app-coordination#19]
The **very long** welcome message is killing for an usable view on an issue, <span title="exempli gratia (for example)">e.g.</span> see #9:
<img alt="screenshot of issue 9" src="https://user-images.githubusercontent.com/4252918/83288565-d87de980-a1e3-11ea-9709-82c339e6b1f5.png" width="332">

To keep it usable it's probably best practice to have a short message, also see [the probot examples](https://probot.github.io/apps/welcome/).

So can we shorten the welcome message by just having a short message with links?
https://github.com/minvws/nl-covid19-notification-app-coordination/blob/1dd5300b41a73d19cfd85d8e8d4b35bfa98844bb/.github/config.yml#L11-L26

**Comment by bwbroersma** [comment]
https://github.com/minvws/nl-covid19-notification-app-coordination/blob/1dd5300b41a73d19cfd85d8e8d4b35bfa98844bb/.github/config.yml#L20
That line definitely can be removed if we just add a few issue templates. And probably app bugs should not be reported in this coordination repository, which can be solved by having a bug report issue template just to redirect people to the correct repository.

**Comment by ijansch** [comment]
Great idea! We’ll improve it.

**Comment by dirkx** [comment]
Nice - @bwbroersma - if you want this faster - just do a PR or add a better Yammel to this ticket.

**Comment by ijansch** [comment]
I shortened the text, but can't test it with my account as it's only shown to first time users.

**Comment by JolandaVerhoef** [comment]
The text was shortened, so I'll close this PR for now. If there's any further issues, please open a new issue for it!
