### ISSUE TITLE
Consider not storing & distributing affected TEKs, but only keeping around bloom filters

### ISSUE THREAD

**Issue by DavyLandman** [minvws/nl-covid19-notification-app-coordination#21]
Or maybe in other words, please consider (or discuss why not picked) design 2 from the [DP-3T white paper](https://github.com/DP-3T/documents/blob/master/DP3T%20White%20Paper.pdf) . At the cost of increased bandwidth, we get unlinkable infections and an easier privacy story:

> This design choice offers several advantages. It prevents adversaries from linking the
ephemeral identifiers of COVID-19 positive users (see privacy analysis for details), and it
enables COVID-19 positive users to redact, after a positive diagnosis, identifiers
corresponding to sensitive locations, times, or periods in which users are certain they
have not been in contact with other people, e.g. while they were alone or behind a
window.

The details are in the paper, but as far as I understand it, instead of storing server side the infected TEKs, and distributing them, we put the infected TEKs on arrival in a bloom filters per the coming 14 days, and per day distribute the relevant bloom filter. Now with correct configuration of the Cuckoo bloom filters you can have very small false-positives, and avoid storing even server-side which TEKs were infected.

**Comment by ijansch** [comment]
That’s a great suggestion! Unfortunately this is not compatible with the Apple/Google protocol as the api only accepts batch files containing TEK keys. See https://static.googleusercontent.com/media/www.google.com/pt-BR//covid19/exposurenotifications/pdfs/Exposure-Key-File-Format-and-Verification.pdf

**Comment by DavyLandman** [comment]
Aha, but isn't there a path to only use the tracking aspect, but do the notification ourselves? The notification form server to client doesn't require access to specific Bluetooth APIs right?

Or are apps not allowed to retrieve the observed TEKs themselfs (the data is private to the apple/Google API)?

**Comment by dirkx** [comment]
Correct. At this time/current version: Apple/Google do not trust anyone - you essentially have to quirt it all down their interface; and they will let you know the results.

**Comment by DavyLandman** [comment]
Ouch, sorry to have bothered you about this, I should have read more about limitations of the API. I naively assumed it was primarily about the Bluetooth access.
