### ISSUE TITLE
Keuze voor 2 native app ipv Flutter

### ISSUE THREAD

**Issue by HofmannZ** [minvws/nl-covid19-notification-app-coordination#29]
Wij volgen de ontwikkelingen van de `nl-covid19-notfication-app` nauw. De open source insteek van het project vinden wij een briljante stap van het Landelijk Operationeel Team Corona.

Wij zijn echter wel benieuwd waarom er wordt gekozen voor het ontwikkelen van 2 native apps i.p.v. één [Flutter](https://flutter.dev) app. Het ontwikkelen van een meerdere apps uit een code base kan dit project helpen om significant sneller de app beschikbaar te maken voor het publiek. Daarnaast bewaakt het de overeenkomst in UI tussen gebruikers op de iOS en Android platforms.

Voor het geval je nog nooit van [Flutter](https://flutter.dev) hebt gehoord, is [Flutter](https://flutter.dev) een open-source, multi-platform mobiele SDK die kan worden gebruikt om iOS- en Android-apps te bouwen met dezelfde broncode. Flutter bestaat al heel lang, maar het begint meer aandacht te krijgen sinds Google I / O 2018 toen Google een release-preview van Flutter aankondigde. Tijdens Flutter Live op 4 december 2018 kondigde Google de eerste stabiele versie van Flutter aan met tal van nieuwe functies. Sommige grote bedrijven zoals Alibaba, eBay, en Square gebruiken het al voor het ontwikkelen van hun mobiele apps.

Op dit moment kun je [Flutter](https://flutter.dev) zien als React Native, maar dan met de volledige ondersteuning van alle native functies.

Wat is de aanleiding om voor het ontwikkelen van 2 native apps?

Misschien hebben wij de discussie gemist, in dat geval lezen wij ons graag nog even verder in (link?).

**Comment by ijansch** [comment]
Bedankt voor je suggestie! Uiteraard overwegen we elke toolkeuze zorgvuldig. De overwegingen die we hebben gemaakt in het architectuur document tav het gebruik van cross platform tools, zijn ons inziens ook op Flutter van toepassing:

https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/architecture/Solution%20Architecture.md#native-vs-hybrid-development
