### ISSUE TITLE
Make sure to not geo-lock the app through Google Play or Apple App Store

### ISSUE THREAD

**Issue by arianvp** [minvws/nl-covid19-notification-app-coordination#43]
Our dear friends in Germany (where I also live as an expat) have launched their app today to the public (yay! :partying_face: ). 

However I tried installing the app today, but Google Play told me "This app is not available in your region" eventhough I live in Germany.  I hoped I could change my region easily in Google Play, but this is not possible without adding a payment method like a credit card.  Also even if you add a payment method and change your country, this can only be done once every 365 days.  Furthermore, changing your Google Play region makes you lose your Google Play credits, as they're not transferable between regions meaning switching actually has a severe monetary cost. It also affects the ability to access your Google Movies and Google Music catalogs.   So I am very much not inclined to touch this setting.

Google's view on how free movement works is not compatible with how it actually works in the EU, which means that many expats can either not install the app due to not wanting to add a payment method, or because they already changed their location in Google Play this year and have their region locked.  The issue at our German collegues is being tracked here https://github.com/corona-warn-app/cwa-app-android/issues/478

I would like to bring this issue to attention at an early point such that the Dutch app does not make the same mistake during launch, as it will hinder adoption as many people will not be able to install the app and will probably get frustrated and not try again later.  The first day of a launch is important and should try to be as flawless as possible :)

Given Netherlands has a very large expat community, I would advise not using Geo-blocks based on billing addresses.

Other countries like Swiss, Itality and Estonia do not impose these kind of geo-blocks and I think the Dutch app shouldn't either.

**Comment by corneliusroemer** [comment]
If we can serve as a negative example and help everyone else avoid this pitfall, it makes me feel slightly less bad about this whole charade in Germany.

**Comment by arianvp** [comment]
I think it's important to learn from each other. That's what open source (among other things) is about right? :)

**Comment by pdehaye** [comment]
Are you sure Switzerland's app is not geoblocked? The discussion here seems to indicate it was still so 3 days ago
https://github.com/DP-3T/dp3t-app-android-ch/issues/52

Indeed, that's what open source is about, and there are many technical and security issues tied to Google/Apple more than anything else, and that should be resolved across countries. 

It boggles my mind that the devs of all those apps haven't yet started a public GitHub to discuss all this with communities of all countries. We would make progress so much faster than chasing different GitHubs across borders. 

Maybe it's up to... us to do this?

**Comment by arianvp** [comment]
SwissCovid was rolled out internationally today

**Comment by JolandaVerhoef** [comment]
Thank you for your input! At this point in time, we're not planning to geo-lock the apps through Google Play or the Apple App Store.

**Comment by corneliusroemer** [comment]
@JolandaVerhoef That's amazing! Make sure you do a quick legal assessment though of whether what the Germans are doing is necessary. They are adamant that it is but haven't offered any hard evidence yet.

Maybe reaching out to RKI would be a thing to try. The German community is putting out freedom of information requests but this will take longer than just a quick friendly email from GAEN team NL :)

I would clear it internally with the ministry's legal team early on, I'd actually ask right now, so that they don't realise it last minute that they in fact need to do something that they could have started a month before. That's I think what happened in Germany. Ignorance among department lawyers on app store practices, and silence/ignorance on the part of the contractors not preemptively bringing attention to the issue. You've been warned 😂

**Comment by dirkx** [comment]
We're going to try to do this right - and we're not planning a geo-lock. But this is not something entirely under our control; apple & google control these gates tightly -- and this type of app is special. So lets close this for now - and we'll re-open if we need help to work around obstacles.

**Comment by arianvp** [comment]
Sounds good. Happy that it's at least on the radar as an issue and let's
hope we can get it rolled out to as many Dutch citizens as possible :)
