### ISSUE TITLE
[2020-07-08]: [VWS/Covid19NotificationApp] Code quality / Static Analysis

### ISSUE THREAD

**Issue by wilgert** [minvws/nl-covid19-notification-app-coordination#54]
A static analysis tool that ensures code quality should be used in all repo's containing source code.
Something like https://bettercodehub.com/ or SonarCube comes to mind.

(I just ran BetterCodeHub on a fork of the Backend repo, this is the score: [![BCH compliance](https://bettercodehub.com/edge/badge/wilgert/nl-covid19-notification-app-backend?branch=master)](https://bettercodehub.com/))

**Comment by ijansch** [comment]
We are running SonarCube on the internal repo; Dirk-Willem can share some details about that.

**Comment by dirkx** [comment]
Aye - we're running these.  Unfortunately - the system at the BD is not very tuned & it is a bit hard for the hoster to tweak false positives (e.g. flag like 'warnig: XXX disabled' near a line such as `if config.debug > 9 doXXX;`.

The green dots are the actual code we have. Same code as in github. 

<img width="1060" alt="sample" src="https://user-images.githubusercontent.com/392583/87664613-d822b900-c765-11ea-85a7-811243dfa504.png">

But beware - this is system is badly tuned; and is IMHO somewhat overly positive.

So these greens certainly does no mean we're happy with the code - but we're focusing on getting it to work in the given system at the BD first & doing field tests. 

Expect full core reviews of this by external parties at some point soon to surface too.
