### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by TeunVR** [minvws/nl-covid19-notification-app-coordination#6]
Copy of https://github.com/minvws/nl-covid19-notification-app-design/issues/10

Het vrijgeven van de source-code van de covid-notification app is belangrijk voor de acceptatie ervan.
Het is echter niet eenvoudig om te verifiëren dat de binary die in de App Store en Play Store staat ook werkelijk op basis van die source-code is gebouwd.

Andere projecten (bv Signal en Telegram) staan voor dezelfde uitdaging:
signalapp/Signal-iOS#641
https://core.telegram.org/reproducible-builds#reproducible-builds-for-ios

Helaas lijkt er niet direct een technische oplossing hiervoor te zijn.
Misschien is het een idee om dit procesmatig in te regelen.
Bv door onafhankelijke “getuigen” tijdens bouwen/submitten naar stores?

**Comment by bwbroersma** [comment]
It's not only having reproducible builds, but also submitting the builds to a non-changeable log, e.g. use [Certificate Transparency](https://www.certificate-transparency.org/what-is-ct) to publish the sha2 hash of the published build as a subdomain (with a SSL certificate). This is the ProtonMail way of doing it, see a FOSSDEM 2020 talk [Building a Web App that Doesn’t Trust the Server - Securing ProtonMail](https://fosdem.org/2020/schedule/event/dip_securing_protonmail/), [slide 8-11](https://fosdem.org/2020/schedule/event/dip_securing_protonmail/attachments/slides/4057/export/events/attachments/dip_securing_protonmail/slides/4057/Building_a_Web_App_that_Doesnt_Trust_the_Server.pdf) and [video recording](https://ftp.fau.de/fosdem/2020/UA2.220/dip_securing_protonmail.mp4) from 5:07 to  11:27.

**Comment by lwesterhof** [comment]
Signal for Anroid has reproducible builds: https://github.com/signalapp/Signal-Android/blob/master/ReproducibleBuilds.md (https://signal.org/blog/reproducible-android/)

**Comment by TeunVR** [comment]
Yes Android looks a bit less complicated in this case. 
For iOS it is pretty hard to compare the binary from the AppStore to a self-built binary.

**Comment by ruuda** [comment]
[The F-Droid Android app store does support reproducible builds](https://f-droid.org/en/docs/Reproducible_Builds/).

**Comment by dirkx** [comment]
Ah - lovely - so that would be a very worthwhile PR once we have the android code base up.

**Comment by dirkx** [comment]
Now that the first code repo's have gone up; with the rest to follow in the next days - I am going to close this one; and PR's for reproducible builds are more than welcome at the code repos. Hope you do not mind. And thanks for sharing and contributing this good suggestion.

**Comment by TeunVR** [comment]
I suggest to keep this issue open until the real app repos are available and then move the issue to the final app repos.
The current app repos are only for lab testing and not the final app.
Otherwise we keep making and closing issues, losing the discussion with it.

**Comment by dirkx** [comment]
Fair point.

**Comment by ijansch** [comment]
The term ‘reproducible builds’ is confusing. The thing the developers need to do to make their build reproducible is, if I understand correctly, to only publish which version of the source was used for a particular App Store build. The other parts in the linked examples above are the tasks that a verifier must perform to actually reproduce the builds. As such, these documents describe how to reproduce builds. Correct? I’m wondering if the instructions on how to reproduce the build should be documented as part of the source itself, since it includes the instruction to jailbreak a device, which can be considered harmful.

**Comment by TeunVR** [comment]
"Reproducible builds" is a common term used for the verification of pre-compiled binaries.
https://reproducible-builds.org

The idea is that anybody can build the same sources and get the same binary. The precompiled binary and self-built binary can then be compared (hash) to check wether the precompiled binary was in fact built with these sources.

The challenge in the case of iOS and Android is that it is hard or even impossible to get access to the binary from the AppStore / PlayStore and even if you get access the binary might be different (bitcode etc).

So the challenge is to either find a legal way to compare store-binaries or to implement a process where the builds are verified by independent parties before submitting to Apple/Google.

**Comment by arianvp** [comment]
Also see the technical documentation of the Italian colleagues. 

https://github.com/immuni-app/immuni-documentation/blob/master/Technology%20Description.md#reproducible-builds

**Comment by ijansch** [comment]
Top, bedankt voor deze toelichting. Ik ga kijken hoe we dit kunnen faciliteren. Als iemand daarbij wil helpen, qua opzeggen van de juiste tooling, graag.

**Comment by jellelicht** [comment]
@ijansch how do you see this happening exactly? Who/which group is currently responsible for creating the eventual releases?

**Comment by jellelicht** [comment]
Some teams have made some leeway with this here:  https://github.com/DP-3T/dp3t-app-android-ch/blob/master/REPRODUCIBLE_BUILDS.md .

**Comment by jellelicht** [comment]
I think now is the time to make this happen (or not).
@ijansch very simple question: is there buy-in from all the relevant stakeholders on the internal side of things? 

Sadly, this is one of the aspects that is very much only feasible to do once we know the _exact_ build procedures used internally before pushing to Play store, so I think outsiders can't do much besides cheering and sharing relevant resources ;-).

**Comment by hvisser** [comment]
I know this won't be sufficient for what you're asking, but we're automating deploys to the Play Store and these build numbers relate to the build numbers on our CI. So it's not possible to upload a build with the same build number after the fact (Play Store won't allow this), nor is it possible to preempt an upload with a newer build number (our build will break).

**Comment by jellelicht** [comment]
@hvisser this is actually already a good step in the right direction; the most important piece of information left is sharing your build steps + build tools. For a typical CI system that usually boils down to the used container images, git checkout of the sources and the actual build instructions.

**Comment by hvisser** [comment]
Agreed, for Android it's pretty much one gradle command since the build tools etc are locked on a specific version already (tied to the AGP version) but we should document those steps. Recently we've added flavours to make it easier as well to reproduce a specific build.

**Comment by arianvp** [comment]
> Gedurende de bouw zijn er voortdurend tests uitgevoerd naar de technische werking van de app. Om te bewijzen dat de versies van de apps die naar Google en Apple worden gestuurd 1-op-1 gebaseerd zijn op de versies die zijn gepubliceerd op GitHub, zijn door de Landsadvocaat in samenwerking met een zogenaamde “Escrow partij” (Escrow Alliance) validatiecontroles uitgevoerd. Voor elke versie van elke applicatie zal een verklaring van juistheid en integriteit worden afgegeven. 

https://www.tweedekamer.nl/kamerstukken/brieven_regering/detail?id=2020Z14096&did=2020D29955

**Comment by jsoeterbroek** [comment]
With the merge of PR minvws/nl-covid19-notification-app-ios/pull/20 continuous integration testing & reproducible builds is now available to the iOS app as well, trough Github Actions workflow.

**Comment by arianvp** [comment]
I don't see how that PR solves the reproducible builds question. It allows us to _build_ but there is no infrastructure to test whether the build is actually reproducible.

However; I think as OP suggested having an Escrow partner (and as also suggested as a solution to Parliament in the linked documented) is a good middle-ground that takes away many of the risks.

**Comment by jellelicht** [comment]
If an Escrow partner can do this, so can the community, right?
Why not both? 

@jsoeterbroek is this Github Action the exact way that the _release_ build of the application is made as well? Because then it is at least technically possible to have the App Store builds verified as well, and then the iOS part is done :fireworks: 

(NB: Escrow for the server side of this all makes a lot of sense, so major :+1: for that)

**Comment by dirkx** [comment]
Yup -  most certainly. We're working on cleanly triggering the builds; and hope to get to a stage where both are possible against same tag & comparable & publicly observable.

**Comment by jsoeterbroek** [comment]
> I don't see how that PR solves the reproducible builds question. It allows us to _build_ but there is no infrastructure to test whether the build is actually reproducible.
> 
> However; I think as OP suggested having an Escrow partner (and as also suggested as a solution to Parliament in the linked documented) is a good middle-ground that takes away many of the risks.

It's a start.

**Comment by jsoeterbroek** [comment]
> @jsoeterbroek is this Github Action the exact way that the _release_ build of the application is made as well? Because then it is at least technically possible to have the App Store builds verified as well, and then the iOS part is done 

I have no way of knowing. I am a volunteer contributer and I have no insight into how the internal _release_ build of the application is made.

**Comment by jellelicht** [comment]
@jsoeterbroek that was a misunderstanding on my part then. When you mentioned reproducible builds being available, I'd assumed you meant something you didn't mean to say.

**Comment by arianvp** [comment]
Do we agree we can close this now that escrow has been chosen as the path to tackle this risk?

**Comment by arianvp** [comment]
See https://github.com/minvws/nl-covid19-notification-app-provenance

Cc @dirkx

**Comment by dirkx** [comment]
Agreed. This can be closed.

**Comment by TeunVR** [comment]
Agreed. Thanks.

**Comment by dirkx** [comment]
Beetje jammer wel. Rep. builds waren mooier geweest. Volgende project :)

**Comment by hvisser** [comment]
We zijn heel dichtbij volgens mij, dus als je nog wat tijd overhebt @dirkx 😇
