### ISSUE TITLE
K

### ISSUE THREAD

**Issue by jan389** [minvws/nl-covid19-notification-app-coordination#71]
### Describe the bug, issue or concern

A clear and concise description of what the bug, issue or concern is is.

E.g. 

### Screenshots

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

### Governance
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by ijansch** [comment]
Dummy issue? Closing.
