### ISSUE TITLE
Provide alt texts for images in the Solution Architecture document.

### ISSUE THREAD

**Issue by ijansch** [minvws/nl-covid19-notification-app-coordination#9]
Mentioned by @bwbroersma in a pull request. I made this ticket because I couldn't fix it right away. For now, we are syncing the architecture doc from a google doc using https://github.com/mangini/gdocs2md - I have to check how I can easily add them to the flow.

**Comment by bwbroersma** [comment]
I asked about that syncing yesterday in https://github.com/minvws/nl-covid19-notification-app-coordination/pull/12#issuecomment-635501018:
> @ijansch now that it is on GitHub in Markdown you're not going to sync it back to Google Docs I hope?

Is it needed to keep documents in sync with Google Docs or was it an one-time export?

**Comment by ijansch** [comment]
I added all alt texts in the latest version of the doc that is currently in PR#34.
